Codewars/codewars-runner-cli

- jvm-runner/project.clj
- lib/runners/clojure.js
- lib/runners/groovy.js
- lib/runners/java.js
Updated Clojure to version 1.8 and bumped jvm-runner project version from 0.1.1 to 0.1.2
> Updated Clojure

- jvm-runner/src/java/codewars/java/CwRunListener.java
Preventing failure.getMessage to show empty message.
Code runs faster if you define a variable value only once ( final reserved word constraints compiler  to define only once in case of future modifications).
I haven't runned so please review on any branch first :$
> Avoid DD + empty string

- lib/runners/dart.js
- test/runners/dart_spec.js
**Fixes:**
- #189 Check for `warning:` or `error:` to output the error text for tests flagged as in error
- #191 Include `isFailure === false` when determining if result is an error or test failure
**Other Changes:**
- Use sync file writing as per most of the other runners since there is an occasional issue where some files are not written fully before accessed. As other runners use sync write I implemented the same rather than callbacks or promisifying it
- Added test case for #189 fix
- Added test case for #191 fix
> Fixes testing output for failures and errors

- lib/shovel.js
- package.json
- test/runners/cpp_spec.js
escapes stderr output so it's not interpreted as HTML
> Escape stderr 

- examples/php.yml
- frameworks/php/phpunit/CodewarsListener.php
- frameworks/php/phpunit/phpunit.xml
- test/runners/php_spec.js
- Had to override the built-in test printer with our own, which prints nothing
- Also fixed issue where PHPUnit rendered success even when there was a failure
> Fixed PHPUnit printing extra dots

- frameworks/cpp/igloo/core/contextregistry.h
- test/runners/cpp_spec.js
- uses a list instead of a map so specs will run in the written order
> Bug/CPP Tests Run Alphabetically

- lib/runners/clojure.js
- test/runners/clojure_spec.js
Clojure was escaping line breaks, causing passed/failed tokens to be treated as non-data. This is a hacky fix since i don't understand clojure well enough to fix it properly. Also cannot determine what changed that would have caused this.
> clojure fix (HACK)

- lib/runners/javascript.js
- test/runners/javascript_spec.js
Mocha was not adding semicolons between code segments, which could cause errors if the trailing content looked like the start of a function.
> Fix for Mocha runner and lack of trailing semicolons.

- jvm-runner/project.clj
- jvm-runner/src/java/codewars/java/CwRunListener.java
- jvm-runner/test/codewars/runners/java_test.clj
- lib/runners/clojure.js
- lib/runners/groovy.js
- lib/runners/java.js
- test/runners/java_spec.js
- HTML Escapes `<` and `>` within descriptions, errors and failures
- Renders runtime exceptions if the error was not an assertion error
> Improved JVM runner output:

- frameworks/php/phpunit/CodewarsListener.php
- frameworks/php/phpunit/phpunit.xml
- lib/runners/php.js
- test/runners/php_spec.js
- Fixes bug causing PHP errors to get swallowed, also swallowing the `<FAILED::>` tag
- Was caused by overzealous blacklist, those lines are now cleaned up without filtering them out
- Adds newlines before each test result, to make sure that echoing content without a newline doesn't swallow answers
> Improved PHP runner output. Fixes #221 and #223

- docker/python.docker
Codewars does not have a ton of cryptography katas (especially those which relate directly to practical, modern crypto), but I hope to help change that because practical modern crypto is an extremely important topic.
gmpy2 will help with high precision arithmetic needed when performing operations on very large numbers, such as in cryptography. However, it may also come in handy in other types of katas that involve working with extremely large numbers.
PyCrypto will also give users access to basic crypto functions/algorithms that are missing in Python, since Python's built-in crypto is limited to the hashlib and hmac libraries, which is insufficient.
> Adding gmpy2 and PyCrypto to python.docker

- docker-compose.yml
- lib/runners/fsharp.js
- lib/runners/ocaml.js
I've updated the `ocaml.js` runner file to call the bash script that sets up environment variables properly; mocha tests still pass, and I can now `docker-compose run ocaml-runner -c 'print_endline "Hello World!";;'` and see output (before I saw no output when I tried to do that).
> Ocaml: Should fix 'spawn utop ENOENT'; Ocaml/FSharp: fix support for 'Preloaded' code

- lib/runners/c.js
Added the -lm flag to the "args" array in the solutionOnly function to provide math library linkage.
Earlier, I overlooked the "args" array in the solutionOnly function and only added the "-lm" flag to the "args" array in the testIntegration function. Hope this finally resolves
https://github.com/Codewars/codewars.com/issues/658
If not, please let me know. Thank you.
> Added the -lm flag to the args array in the solutionOnly function

- README.md
Changed Docker image for Clojure language name to 'jvm-runner' from 'func-runner'
> fixed Docker image name for Clojure in README.md

- .travis.yml
- Makefile
- docker/haskell.docker
- frameworks/haskell/Test/Hspec.hs
- test/runners/haskell_spec.js
`docker/haskell` can now build with `make haskell`
`test/runners/haskell_spec.js` update due to signature mismatch of different hspec version. 
It pass all test in `test/runners/haskell_spec.js` but I have to double the timeout because my machine is slow. The longest test need 9s to complte. (#260 -related)
haskell [lts-1.0](https://www.stackage.org/lts-1.0) is minimum version that has all packages require.
I'm currently test if I can push haskell system to newer version. 
For now, please use this image.
> fix haskell docker build failed

- .travis.yml
- Makefile
- docker/haskell.docker
- frameworks/haskell/Test/CodeWars/BlackList.hs
- frameworks/haskell/Test/Hspec.hs
- test/runners/haskell_spec.js
Update haskell system to newer [lts-6.24](https://www.stackage.org/lts-6.24) version (compared to #270)
Please murge this to a new `feature/haskell-7.10` branch while testing #270 (2ede419) on master.
This commit contain non-trival change to codewars's haskell framework. 
I have no idea how to fully test it beside `test/runners/haskell_spec.js` on `docker build`
> feature/haskell 7.10

- frameworks/c/criterion.c
- test/runners/c_spec.js
This adds the exit code and signal to the Test Crashed report message
> Criterion signal support

- docker/ruby.docker
Hello,
This adds an update to install two extra packages that are used everyday to extend the functionality of the shell. Bc (basic calculator) allows for complex math functions to be performed, as well as allowing the shell to support floating-point numbers. The mlocate package contains the locate command, allowing for files to be quickly indexed. The absence of mlocate has been pointed out to me before: https://www.codewars.com/kata/bash-basics-check-for-file-existence/discuss/shell.
Thanks,
DHDawson
> Add bc & mlocate to shell

- Makefile
- frameworks/javascript/display.js
- lib/runners/javascript.js
- test/runners/javascript_spec.js
Fixes #259 by *detecting* reassignment of `global`.
This does not prevent reassignment, but prevents cheating by throwing `Error` with message `"global was reassigned"`.
@jhoffner, do you think throwing error is valid approach?
/cc @Freywar
---
I tried `Object.freeze(global.global)` at first and found several accidental global variables. I also included fixes for those in this pull request. I decided not to use `Object.freeze` because it broke the test "should handle outputting objects with 0.10.33" and will invalidate many solutions. Not adopting suggested fix using `this` because it will fail in strict mode.
> Fixes #259 - cheating by reassigning 'global'

- lib/runners/objc.js
- test/runners/objc_spec.js
Add new clang compiler option (-lm) for the handling math function from
the standard library <math.h>; add an appropriate test.
> [ObjC] Add handling for math functions from standard library

- Makefile
- docker/go.docker
Upgrade to [Go 1.8](https://golang.org/doc/go1.8) as planned. Simply replacing 1.7.5 with 1.8 should be [fine](https://golang.org/doc/go1compat).
> Upgrade to Go 1.8

- Makefile
- docker/alt.docker
- Remove Go and Lua
- Fix the unicode [issue](https://github.com/Codewars/codewars-runner-cli/pull/320#issuecomment-285130208) in `RUN add-apt-repository ppa:ondrej/php`
- Fix the issue with phpunit caused by not specifying the version
> Fix alt-runner

- .dockerignore
Remove `.git` (and `.DS_Store`) from build context.
---
I'm going to look into reducing image sizes.
For `alt-runner`, `/frameworks` is `46M`, but only `/frameworks/php` (`24K`) is used.
I think modifying `.docker` files will be the easier than maintaining separate `.dockerignore`.
> Remove .git from build context

- .eslintignore
- .eslintrc.yml
- Makefile
- frameworks/javascript/karma-coderunner-reporter.js
Start using [ESLint](http://eslint.org/) with this simple configuration and configure as necessary:
```yaml
root: true
env:
es6: true
node: true
mocha: true
extends: 'eslint:recommended'
rules:
indent:
- error
- 2
linebreak-style:
- error
- unix
quotes:
- off
semi:
- error
- always
no-console:
- off
```
Indentation can be fixed by using `eslint --fix`. This doesn't seem to fix the comments so I need to look into this or fix comments manually.
> Start using ESLint

- Makefile
- frameworks/javascript/cw-2.js
- test/runners/javascript_spec.js
Use `Math.floor(101*Math.random())` to fix the non-uniform distribution.
> Fix Test.randomNumber()

- frameworks/javascript/cw-2.js
- test/runners/javascript_spec.js
> Includes:
>
> - 2 new assertions `Test.assert(Not)ApproxEquals` which follow the general format presented in `cw-2.js`. Compatible with Node v0.10.0
> - Tests in `javascript_spec.js` to confirm that this assertion works as expected
Authored by @DonaldKellett.
> Add Test.assert(Not)ApproxEquals for floating point values

- .travis.yml
`make recent` is executed even if `eslint '**/*.js'` reports errors, but the build will result in failure.
I thought this is less annoying, but if failing quick is preferred, `eslint '**/*.js' && make recent` should do that.
Closes #340 once all other ESLint PRs are merged and this build succeeds.
> Make Travis Check ESLint

- .travis.yml
Skipping Swift because it timeouts. See my newest comment on #328.
Python is failing because `IPython` had a major version increment dropping support for older Python. Some other packages are failing too.
> Use Travis build matrix

- docker/lua.docker
- frameworks/lua/codewars.lua
- lib/runners/lua.js
- test/runners/lua_spec.js
This adds support for `opts.setup` and `opts.dir`.
The code is written to a file named `setup.lua` in `opts.dir` and can be used by `require 'setup'`.
This also fixes the LF issue.
> [Lua] Add "Preloaded" code support

- frameworks/elixir/cw_formatter.ex
- frameworks/elixir/cw_runner.ex
- test/runners/elixir_spec.js
This *should* fix the LF issue for Elixir.
Not tested because `erlang` image is suspended?
#410
> [Elixir] Fix LF issue

- .travis.yml
ESLint 4.0.0 was released on 2017-06-11 and introduced breaking changes.
Use ESLint 3.19.0 for now.
- http://eslint.org/blog/2017/06/eslint-v4.0.0-released
> Lock ESLint version to 3.19.0

- docker/chapel.docker
- docker/crystal.docker
- Thanks to kazk for getting the majority of the work done on this.
- I had to add `shards` to the path binaries to get it to build.
- The `crystal` inside `embedded/bin` is not the same, and could not run the code. Very weird.
I also went ahead and doubled Chapel's timeout within the Docker build, simply to avoid further headaches. This doesn't affect Chapel itself anywhere else, only during the build test. Hopefully 10s is enough.
> Fixes Crystal by installing a specific version

- .travis.yml
- Makefile
- docker/julia.docker
- documentation/environments/julia.md
- frameworks/julia/Test.jl
- lib/runners/julia.js
- test/runners/julia_spec.js
- updated julia.docker (v.0.6.0)
- updated  julia_spec.js
- updated julia.yml
- updated Test.jl 
```julia
it('should handle basic code evaluation', function(done) {
runner.run({
language: 'julia',
code: 'print("42")'
}, function(buffer) {
expect(buffer.stdout).to.equal('42');
done();
});
});
```
generates the following error when run the file julia_spec.js:
```julia
1 failing
1) julia runner .run should handle basic code evaluation:
Uncaught AssertionError: expected '' to equal '42'
+ expected - actual
+42
at test/runners/julia_spec.js:12:34
at lib/shovel.js:28:5
at complete (lib/shovel.js:281:5)
at ChildProcess.<anonymous> (lib/shovel.js:252:5)
at maybeClose (internal/child_process.js:877:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
> Support for julia 0.6

- .travis.yml
This improves Travis build time by using `--cache-from`.
`python-runner` [22 min 18 sec](https://travis-ci.org/Codewars/codewars-runner-cli/jobs/229500520) to [2 min 51 sec](https://travis-ci.org/Codewars/codewars-runner-cli/jobs/229584747)
`haskell-runner` [27 min 41 sec](https://travis-ci.org/Codewars/codewars-runner-cli/jobs/229500534) to [2 min 54 sec](https://travis-ci.org/Codewars/codewars-runner-cli/jobs/229584756)
Duration [44 min 59 sec](https://travis-ci.org/Codewars/codewars-runner-cli/builds/229500514) to [23 min 53 sec](https://travis-ci.org/Codewars/codewars-runner-cli/builds/229584743)
This can be further improved by refactoring Dockerfile to only copy necessary files (removing `COPY . /runner`) which minimizes the number of affected images.
Also, some images are failing to …
> Improve Travis build time

- lib/runners/haskell.js
- test/runners/haskell_spec.js
#271 broke existing kata that contained Tabs (https://github.com/Codewars/codewars.com/issues/700) because "-fwarn-tabs warning flag is turned on by default" since [GHC 7.10.1](https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/release-7-10-1.html#idp5793824).
This disables the warning. Maybe remove this later if existing kata can be migrated.
Closes https://github.com/Codewars/codewars.com/issues/700
> [Haskell] Disable warning on Tab usage

- lib/runners/swift.js
- test/runners/swift_spec.js
> Fix Swift compatibility issue around XCTMain

- docker/rust.docker
- examples/rust.yml
- frameworks/rust/skeleton/Cargo.toml
- frameworks/rust/skeleton/src/lib.rs
- lib/runners/rust.js
- test/runners/rust_spec.js
This should allow writing random tests using `rand` (#240).
I had to come up with a backward compatible way, and I'd like feedbacks from Rust users.
- Use Cargo
- Install `rand` package
- Improve output
- Align with other languages
- Include stdout of failed tests
- Proper termination
- Include examples to tests
- Restructure tests by context
Needs some hack in order to maintain backward compatibility and avoid errors with duplicate import.
.
|- Cargo.toml
`- src
|- lib.rs    (opt.setup + opts.solution + module declaration)
`- tests.rs  (opts.fixture)
- Placing `opts.fixture` in submodule `tests.rs` should avoid issues with duplicate imports
- Maintains backward compatibility by prepending `use super::*;` to `opts.fixture` if missing
Another idea was
.
|- Cargo.toml
`- src
|- lib.rs …
> Rewrite Rust runner

- lib/runners/typescript.js
- test/runners/typescript_spec.js
Make `tsc` `--target` configurable through `opts.languageVersion`, e.g., `2.4/ES6`, for simple execution and testing with mocha.
I decided not to touch Karma's configuration for now since it's set to ES5 explicitly.
Closes #418
Closes #380
> [TypeScript] Make targets configurable

- docker/alt.docker
This was part of https://github.com/Codewars/codewars-runner-cli/pull/469/commits/fc97d4767a8365de645a78d268676a7c590455c9, but apparently got lost while merging.
Maybe we should rename `alt-runner` to `php-runner` and `jvm-runner` to `clojure-runner`.
> Remove R installation from alt-runner

- package.json
- test/runners/javascript_spec.js
`DeprecationWarning` in `mongoose >= 4.11.0` breaks existing content.
Filtering out `DeprecationWarning` in general will be separate issue.
> Lock mongoose version to 4.10.x

- frameworks/ruby/sql.rb
- test/runners/sql_spec.js
Note that Travis is not running `sql_spec.js` because I haven't figured out why https://github.com/Codewars/codewars-runner-cli/pull/482#issuecomment-320389834 happens yet. I have tested on my machine that this fix disables the warning.
Closes https://github.com/Codewars/codewars.com/issues/1076
> [SQL] Silence Sequel deprecation warning

- .gitignore
- docker-compose.yml
- docker/gradle.docker
- frameworks/gradle/build.gradle
- frameworks/gradle/gradle.properties
- frameworks/gradle/prewarm.sh
- frameworks/java/prewarm.sh
- lib/runners/groovy.js
- lib/runners/java.js
- lib/runners/kotlin.js
- lib/runners/scala.js
- lib/utils/when-prewarmed.js
- test/runners/groovy_spec.js
- test/runners/kotlin_spec.js
- test/runners/scala_spec.js
- when-prewarmed utility added to ensure we wait until the starting daemon is ready
- cleaned up test cases
- improved test case prewarm integration
- increased jvm memory
> Gradle Optimization Improvements

- docker/objc.docker
Reduce uncompressed size from 2.94 GB to 1.93 GB by removing unnecessary files in the same layer. We can reduce further by identifying dependencies only needed during build and removing them, but I don't have enough knowledge at the moment.
> Refactor objc.docker

- documentation/environments/node.md
- lib/runners/typescript.js
- test/runners/typescript_spec.js
- Now the `languageVersion` is not passed into the Karma/Node runner code, so we don't get Node version errors.
- Updated Node docs to mention Karma testing on TS
> Fix to enable running TS/Karma with a version

- docker/r.docker
Fix apt-get install error:
```
The following packages have unmet dependencies:
r-base : Depends: r-recommended (= 3.4.1-2trusty0) but 3.4.2-1trusty1 is to be installed
```
To be honest, I'm not sure why `3.4.1-*` isn't working, but changing that to `3.4.*` seems to fix it. Also adding `r-base-dev` because I saw this in the documentation:
> Users who need to compile R packages from source [e.g. package maintainers, or anyone installing packages with install.packages()] should also install the r-base-dev package:
> Fix r-base install

- frameworks/java/src/test/java/CwRunListener.java
- lib/runners/java.js
- test/runners/java_spec.js
- Assertion ExceptionDetails logs are less verbose
- Spring boot logs are now collapsed by default
> Java Output Cleanup

- docker-compose.yml
Fix tests failing due to `/runner/frameworks` replaced with bind mount.
> Fix `docker-compose run javascript_test`

- package.json
Might as well update JSDom to the latest version before we start utilizing it. 
**Note** that if someone somewhere did reference this version in a challenge, the API has breaking changes but can still be accessed. [See changelog](https://github.com/tmpvar/jsdom/blob/master/Changelog.md#1000)
> Updated JSDom to latest version

- lib/runners/typescript.js
- test/runners/typescript_spec.js
`/workspace/spec.ts` left from test cases causes strange errors when running TypeScript with Karma. This resolves the issue by removing files after each test case. Also disables instrumentation.
---
```
27 10 2017 21:28:17.613:ERROR [compiler.karma-typescript]: spec.ts(8,58): error TS2339: Property 'a' does not exist on type 'typeof "/home/codewarrior/solution"'.
```
This is caused by `spec.ts` containing `require('./solution')` which is overwritten by submitted code and does not export `a`.
```
27 10 2017 21:28:17.618:ERROR [compiler.karma-typescript]: ../../runner/typings/chai/index.d.ts(386,18): error TS2300: Duplicate identifier 'AssertionError'.
```
`error TS2300` is caused by including the type definition in `fixture.spec.ts` and `spec.ts`.
> Fix karma-typescript errors

- docker/rust.docker
- lib/runners/rust.js
Change in RUSTFLAGS causes everything to be recompiled.
Avoid this by setting it before downloading and compiling crates.
---
It's hard to measure the performance penalties of crates being recompiled, but on Travis
https://travis-ci.org/Codewars/codewars-runner-cli/jobs/284824746#L845-L848
became
https://travis-ci.org/kazk/codewars-runner-cli/jobs/291411040#L842-L845
https://travis-ci.org/Codewars/codewars-runner-cli/jobs/291417135#L843-L846
Note that only the first test case is relevant because tests share the container.
---
The effect should be even more significant on less powerful machines.
#534
> [Rust] Avoid crates to be recompiled

- frameworks/python/codewars.py
- lib/runners/python.js
- test/runners/python_spec.js
This is based on #347, but tries to be drop-in replacement. It passes all the tests, but needs further tests against existing contents.
Only Python 3 for now. I'm hoping this is compatible with Python 2 without much change.
I remember having some issue when doing #347, but I don't remember the details since it's been a while and I didn't document them :|
---
Features:
- No file concatenation
- Prepends few lines if necessary to support existing contents. See below.
- Show file name and line numbers
- Test duration for each block
- Arbitrary test class name
- Multiple test suites
- Needs more work.  Tests are loaded, but combined into one suite
---
To be backwards compatible, few lines are prepended when necessary:
- prepend `import unittest` to fixture if missing
- prepend `from solution …
> Add Python 3 unittest runner without concatenation

- lib/runners/objc.js
- test/runners/objc_spec.js
Make `solution.m` to only contain `opts.solution` and let `fixture.m` handle importing `setup.m`.
Resolves https://github.com/Codewars/codewars.com/issues/1221
> Fix UnitKit with setup code

- examples/python.yml
- examples/python3.yml
- frameworks/python/cw-2.py
- frameworks/python3/cw-2.py
- test/runners/python_spec.js
This PR introduces many improvements based on the discussions at #569 and [my own Kumite](https://www.codewars.com/kumite/5a724cec4a6b34f5d00000ba?sel=5a724cec4a6b34f5d00000ba).
---
* Make testing functions non-blocking
* Change the expression inside `assert_not_equals` so that it can prevent operator injection hacks
* Provide `pass_`, `fail`, and `assert_approx_equals` with customizable precision (`pass` is a Python keyword)
* Replace hardcoded `print`s with `display`
* Build the decorator version of `describe` and `it`, so the text fixture may look like this (and the decorator itself runs the code, so it doesn't need a separate runner function):
```python
@describe('describe-text')
def describe1():
@it('it-text', before=f1, after=f2)
def it1():
@it('it-text')
def it2():
```
* Properly …
> Improved cw-2.py
