- jvm-runner/README.md
now they should redirect correctly
> fix links on readme

- .travis.yml
- Makefile
- lib/runners/elixir.js
- lib/runners/javascript.js
- lib/runners/typescript.js
- package.json
- updated lodash
- mocha's timeout has been extended
- elixir code cleanup
> Misc updates

- frameworks/cpp/igloo/core/contextregistry.h
- frameworks/cpp/igloo/core/testlistener.h
- frameworks/cpp/igloo/core/testlisteneraggregator.h
- frameworks/cpp/igloo/core/testlisteners/minimalprogresstestlistener.h
- frameworks/cpp/main.cpp
- lib/runners/cpp.js
- test/runners/cpp_spec.js
> Issue #187 Handle multiple spec errors

- README.md
- docker-compose.yml
- docker/alt.docker
- examples/php.yml
- frameworks/php/phpunit/CodewarsListener.php
- frameworks/php/phpunit/phpunit.xml
- lib/config.js
- lib/runners/php.js
- test/runners/php_spec.js
- Adds both cw-2 ( thanks @DonaldKellett ! ) and phpunit frameworks. 
I am not a PHP developer by any means, learning as necessary, so I'm opening this up for feedback from PHP developers. I'd especially like to know if the PHPUnit implementation is desirable. 
Finishing up work on proper formatting and more specs.
> PHP Support

- README.md
- docker/python.docker
- frameworks/ruby/cw-2.rb
- lib/runners/csharp.js
- lib/shovel.js
- test/runners/cpp_spec.js
- test/runners/elixir_spec.js
- test/runners/erlang_spec.js
- added Python Tornado
- lowered C# warning level
- added ruby `Test.fail` method
- added examples to cpp specs
- fixed erlang/elixir specs due to version update
> Misc Updates and Fixes

- lib/runners/dart.js
- test/runners/dart_spec.js
Adds more tests and changes message splitting regex to capture even more scenarios
> Resolves #201

- jvm-runner/test/codewars/runners/groovy_test.clj
- lib/runners/groovy.js
hope it can make it work again :(
> downgrade groovy runner version

- jvm-runner/test/codewars/runners/groovy_test.clj
Reverts Codewars/codewars-runner-cli#194
> Revert "downgrade groovy runner version"

- examples/rust.yml
> Rust example .yml

- docker/python.docker
- examples/javascript.yml
- frameworks/javascript/cw-2.js
- helpers/javascript/redis-helper.js
- lib/shovel.js
- test/runner.js
- test/runners/javascript_spec.js
- cw-2 now supports async
- added redis helper and tests
- python image now includes django and mpld3
> CW-2 Improvements

- frameworks/python/unittestwrapper.py
- frameworks/python3/unittestwrapper.py
- lib/config.js
- lib/runners/python.js
- test/runners/python_spec.js
- Now includes a fake DESCRIBE and real IT blocks
> Improved Python unittest run output

- Makefile
- docker-compose.yml
- docker/swift.docker
- examples/swift.yml
- frameworks/swift/xctest/PrintObserver.swift
- frameworks/swift/xctest/codewars-build-presets.ini
- lib/runners/swift.js
- test/runners/swift_spec.js
Swift integration for Codewars.
Allows Swift to be used as a programming language for interactive code challenges on Codewars.com
Includes:
- Updated Makefile and docker-compose.yml files to build a "swift-runner" docker image.
- "swift.yml" file with both cw-2 and xctest examples.
- "PrintObvserver.swift" file with Codewars specific test suite stdout format.
- "codewars-build-presets.ini" file to describe how to build Swift from source for Codewars.
- "swift.js" file to allow both cw-2 and xctest code to be run from the CLI.
- "swift_spec.js" file with test cases for both cw-2 and xctest.
> Swift integration

- docker/swift.docker
- frameworks/swift/xctest/PrintObserver.swift
- frameworks/swift/xctest/XCTAssert.swift
- test/runners/swift_spec.js
Swift integration for codewars.
- Includes:
- Removing Swift source files and libraries to save ~4GB of disk space from docker image.
- Adding 'XCTAssert.swift' file to show test results at the assertion level rather than just the test method level.
- Adding a new test in swift_spec.js to test the output for multiple assertions in a single test method.
- Updating swift_spec.js with test for newline
> Swift integration updates

- README.md
- docker/systems.docker
- frameworks/c/criterion.c
- test/runners/c_spec.js
-Readme update
-Test Crashed message and unit test
-Test Timedout message and unit test
-Replace \n with <:LF:> and unit test
-C unit test on docker build
C examples will be added on another PR
> Mixed fixes

- examples/c.yml
- test/runners/c_spec.js
> C examples

- frameworks/javascript/karma-coderunner-reporter.js
- Prevents accidental nesting of describe blocks
> Added in COMPLETEDIN to every "it"

- lib/runners/c.js
http://stackoverflow.com/questions/16370356/how-to-use-clang-compile-c-file-with-math-h
This should potentially resolve this issue:
https://github.com/Codewars/codewars.com/issues/658
> Added the -lm flag to link the math library.

- docker/base.docker
- package.json
- Sets NODE_ENV to development for full error messages
- Adds React Test Utils addon
> React Testing Updates

- lib/shovel.js
- test/runners/c_spec.js
This adds the child_process signal support to the output buffer.
> Shovel signal support

- .gitignore
- Dockerfile
- Makefile
- docker/objc.docker
- lib/runners/objc.js
- test/runners/objc_spec.js
Added Objective C support
Tests will be added soon.
> Added Objective-C Linux support

- documentation/output_format.md
I don't know why line 122 is marked :/
> Fixed typo s/peace/piece

- Makefile
- docker/lua.docker
- documentation/environments/lua.md
- examples/lua.yml
- frameworks/lua/codewars.lua
- lib/runners/lua.js
- test/runners/lua_spec.js
Add [Lua](http://www.lua.org/) support. Uses [busted](https://olivinelabs.com/busted).
This closes #166.
> Add Lua support

- lib/config.js
- lib/copydir.js
- lib/shovel.js
- lib/util.js
Fix some inconsistencies, mainly whitespace. No logic changes.
- lib/config.js
- Fix indentation
- lib/copydir.js
- Fix inconsistent whitespace
- Move default `filter` definition inside the constructor
- lib/util.js
- Remove unused module
- Fix inconsistencies
- Simplify some expressions
- lib/shovel.js
- Fix inconsistent whitespace
- Fix inconsistent braces/semicolons
> Refactor lib/{config,copydir,util,shovel}.js

- Makefile
- docker/python.docker
```dockerfile
RUN ln -s /home/codewarrior /workspace
ADD . /runner
WORKDIR /runner
RUN ln -s /home/codewarrior /workspace
```
> Remove second `ln -s /home/codewarrior /workspace`

- Makefile
- frameworks/javascript/cw-2.js
- Remove `$$_SUCCESS__` and `$STDOUT`
- Add `var` to `describeNext`
- Fix `explain` in `assertNotEquals`
> Fix frameworks/javascript/cw-2.js

- lib/runners/gas.js
- lib/runners/nasm.js
- Fix `linkerCommand` declarations
> Fix lib/runners/{gas,nasm}.js

- Makefile
- lib/runners/fsharp.js
- Fix `xUnitAssembly` declaration
- Remove unused `config`
> Fix lib/runners/fsharp.js

- Makefile
- lib/runners/crystal.js
- Remove unused modules: `config`,`temp`,`child_process`
- Remove unnecessary assignments
> Fix lib/runners/crystal.js

- Makefile
- lib/runners/rust.js
- Remove unused `_formatErr` function
- Remove unnecessary assignments and simplify
> Fix lib/runners/rust.js

- Makefile
- lib/runners/objc.js
- Remove unnecessary assignments and simplify
> Fix lib/runners/objc.js

- lib/runners/coffeescript.js
- test/runners/coffeescript_spec.js
- Fix 'error: missing indentation'
---
Closes #345
> Fix lib/runners/coffeescript.js

- Makefile
- lib/runners/ruby.js
- lib/runners/shell.js
- lib/runners/sql.js
> Fix lib/runners/{ruby,shell,sql}.js

- Makefile
- lib/runners/php.js
> Fix lib/runners/php.js

- Makefile
- lib/runners/dart.js
- Remove unused modules `util` and `config`.
> Fix lib/runners/dart.js

- Makefile
- docker-compose.yml
- documentation/environments/go.md
- lib/runners/go.js
- test/runners/go_spec.js
- Improve documentation
- Update Go version to 1.8
- Remove "Packages" header
- Remove undocumented list of matchers
- Add a link to custom matchers
- Add a section about preloaded code
- Add `docker-compose.yml` services
- Change the solution file to be always 'solution.go'
> Change the filename of the solution to fixed 'solution.go' instead of '{package}.go' to avoid name collision.  Using '{package}.go' will cause issues if the user named the package 'setup' having optional 'setup.go', for example.  This shouldn't change anything because the package path remains the same.
- Improve consistency in tests by always using array to write Go code
- Remove unused function parameters in tests to make ESLint happy
> [Go] Improve documentation and fix minor issues

- Makefile
- lib/config.js
- lib/runners/python.js
- Move boilerplate code inside lib/runners/python.js
- Add the missing colon after COMPLETEDIN
> Remove config.snippets.python

- Makefile
- frameworks/javascript/display.js
- Remove unused module
- Remove unnecessary assignments
- Fix invalid `typeof` comparison value `array`
> Fix frameworks/javascript/display.js

- Makefile
- docker/node.docker
- lib/runners/javascript.js
- lib/runners/typescript.js
> Fix lib/runners/{javascript,typescript}.js

- Makefile
- lib/runners/julia.js
> Fix lib/runners/julia.js

- Makefile
- lib/runners/csharp.js
- test/runners/csharp_spec.js
- Remove unnecessary assignment and commented out code
- Remove unused module in csharp_spec.js
> Fix lib/runners/csharp.js

- frameworks/cpp/main.cpp
- test/runners/cpp_spec.js
This fixes the LF issue for C++.
#410
> [C++] Fix LF issue

- frameworks/ruby/cw-2.rb
- frameworks/ruby/cwrspecformatter.rb
- test/runners/ruby_spec.js
This fixes the LF issue for Ruby.
#410
> [Ruby] Fix LF issue

- frameworks/python/cw-2.py
- frameworks/python/unittestwrapper.py
- test/runners/python_spec.js
This fixes the LF issue for Python.
#410
> [Python] Fix LF issue

- frameworks/php/cw-2.php
- test/runners/php_spec.js
This fixes the LF issue for PHP tests using Codewars framework.
#410
> [PHP] Fix LF issue

- frameworks/crystal/formatter.cr
- test/runners/crystal_spec.js
This fixes the LF issue for Crystal.
#410
> [Crystal] Fix LF issue

- docker/dotnet.docker
- lib/runners/fsharp.js
- test/runners/fsharp_spec.js
This fixes the LF issue for F#.
#410
> [F#] Fix LF issue

- .travis.yml
- Makefile
- docker/erlang.docker
Lock Erlang OTP 18.3, Elixir v1.2.4
Supporting multiple version might be possible using asdf.
- <https://github.com/asdf-vm/asdf>
Resolves #204
> Unfreeze Erlang/Elixir

- docker/alt.docker
- docker/chapel.docker
- docker/crystal.docker
- docker/dart.docker
- docker/dotnet.docker
- docker/esolangs.docker
- docker/go.docker
- docker/haskell.docker
- docker/java.docker
- docker/julia.docker
- docker/jvm.docker
- docker/lua.docker
- docker/nim.docker
- docker/node.docker
- docker/objc.docker
- docker/ocaml.docker
- docker/python.docker
- docker/ruby.docker
- docker/rust.docker
- docker/swift.docker
- docker/systems.docker
This minimizes the number of images affected by change.
Other than that, I had to combine `gem install` in `ruby.docker` to avoid "max depth exceeded" error (too many layers). Also note that C# is not tested.
Closes #471
> Copy only necessary files into images

- frameworks/julia/Test.jl
- test/runners/julia_spec.js
Support for julia 0.6.0
+ updated Test.jl
+ updated julia_spec.js
> julia v0.6.0

- docker/node.docker
- test/runners/typescript_spec.js
Support reference paths under `'/runner/typings/main/ambient/'`
> Add typings/ back

- lib/runners/rust.js
- test/runners/rust_spec.js
Disable this warning for existing contents.
Closes https://github.com/Codewars/codewars.com/issues/1071
> [Rust] Allow `non_snake_case`

- frameworks/javascript/display.js
- frameworks/javascript/mocha-reporter.js
- lib/runners/javascript.js
- lib/runners/typescript.js
- package.json
- test/runners/coffeescript_spec.js
- test/runners/javascript_spec.js
- test/runners/typescript_spec.js
Fixes the LF issue for JavaScript test frameworks Codewars and Mocha.
Also moves `mocha-reporter` from https://github.com/Codewars/mocha-reporter into this repository (https://github.com/Codewars/codewars-runner-cli/issues/410#issuecomment-299358289).
#410
> [JS/TS/CS] Fix LF Issue

- frameworks/ruby/sql/csv_importer.rb
- allow importing files over HTTP
- primary/foreign key config
> Updates to CSV Importer
